// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Spash
void ui_Spash_screen_init(void);
void ui_event_Spash(lv_event_t * e);
lv_obj_t * ui_Spash;
lv_obj_t * ui_SplashVersion;
lv_obj_t * ui_Label2;


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_TabViewSettings;
lv_obj_t * ui_TabPageWifi;
lv_obj_t * ui_WifiSsidLabel;
lv_obj_t * ui_WifiSsidDropdown;
lv_obj_t * ui_WifiPasswordLabel;
void ui_event_WifiPasswordTextArea(lv_event_t * e);
lv_obj_t * ui_WifiPasswordTextArea;
lv_obj_t * ui_TabPageLocation;
lv_obj_t * ui_LocationSearchLabel;
void ui_event_LocationSearchTextArea(lv_event_t * e);
lv_obj_t * ui_LocationSearchTextArea;
lv_obj_t * ui_LocationFoundLabel;
lv_obj_t * ui_LocationFoundValueLabel;
lv_obj_t * ui_LocationLatLonLabel;
lv_obj_t * ui_LabelLatLong;
lv_obj_t * ui_TabPageSettings;
lv_obj_t * ui_SettingsRangeLabel;
lv_obj_t * ui_SettingsRange;
lv_obj_t * ui_SettingsUnitsLabel;
void ui_event_SettingsRangeSlider(lv_event_t * e);
lv_obj_t * ui_SettingsRangeSlider;
lv_obj_t * ui_SettingsImperialLabel;
void ui_event_SettingsImperialSwitch(lv_event_t * e);
lv_obj_t * ui_SettingsImperialSwitch;
void ui_event_SettingsCalibrateButton(lv_event_t * e);
lv_obj_t * ui_SettingsCalibrateButton;
lv_obj_t * ui_SettingsCalibrateButtonLabel;
void ui_event_ButtonCancel(lv_event_t * e);
lv_obj_t * ui_ButtonCancel;
lv_obj_t * ui_ButtonCancelLabel;
void ui_event_ButtonOk(lv_event_t * e);
lv_obj_t * ui_ButtonOk;
lv_obj_t * ui_ButtonOkLabel;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_FlightLabel;
lv_obj_t * ui_Flight;
lv_obj_t * ui_Button2;
void ui_event_Label3(lv_event_t * e);
lv_obj_t * ui_Label3;


// SCREEN: ui_Calibrate
void ui_Calibrate_screen_init(void);
lv_obj_t * ui_Calibrate;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Spash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        OnSplashScreenLoaded(e);
    }
}
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        OnSettingsScreenLoaded(e);
    }
}
void ui_event_WifiPasswordTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_WifiPasswordTextArea);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_LocationSearchTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnCitySearchValueChanged(e);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_LocationSearchTextArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_SettingsRangeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SettingsRange, target, "", "");
    }
}
void ui_event_SettingsImperialSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_SettingsUnitsLabel, _UI_LABEL_PROPERTY_TEXT, "Mi");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_label_set_property(ui_SettingsUnitsLabel, _UI_LABEL_PROPERTY_TEXT, "Km");
    }
}
void ui_event_SettingsCalibrateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnCalibrateClicked(e);
    }
}
void ui_event_ButtonCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Spash, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Spash_screen_init);
    }
}
void ui_event_ButtonOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnSettingsOkClicked(e);
    }
}
void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Spash_screen_init();
    ui_Settings_screen_init();
    ui_Main_screen_init();
    ui_Calibrate_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Spash);
}
