// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Spash
void ui_Spash_screen_init(void);
void ui_event_Spash(lv_event_t * e);
extern lv_obj_t * ui_Spash;
extern lv_obj_t * ui_SplashVersion;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_TabViewSettings;
extern lv_obj_t * ui_TabPageWifi;
extern lv_obj_t * ui_WifiSsidLabel;
extern lv_obj_t * ui_WifiSsidDropdown;
extern lv_obj_t * ui_WifiPasswordLabel;
void ui_event_WifiPasswordTextArea(lv_event_t * e);
extern lv_obj_t * ui_WifiPasswordTextArea;
extern lv_obj_t * ui_TabPageLocation;
extern lv_obj_t * ui_LocationSearchLabel;
void ui_event_LocationSearchTextArea(lv_event_t * e);
extern lv_obj_t * ui_LocationSearchTextArea;
extern lv_obj_t * ui_LocationFoundLabel;
extern lv_obj_t * ui_LocationFoundValueLabel;
extern lv_obj_t * ui_LocationLatLonLabel;
extern lv_obj_t * ui_LabelLatLong;
extern lv_obj_t * ui_TabPageSettings;
extern lv_obj_t * ui_SettingsRangeLabel;
extern lv_obj_t * ui_SettingsRange;
extern lv_obj_t * ui_SettingsUnitsLabel;
void ui_event_SettingsRangeSlider(lv_event_t * e);
extern lv_obj_t * ui_SettingsRangeSlider;
extern lv_obj_t * ui_SettingsImperialLabel;
void ui_event_SettingsImperialSwitch(lv_event_t * e);
extern lv_obj_t * ui_SettingsImperialSwitch;
void ui_event_SettingsCalibrateButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsCalibrateButton;
extern lv_obj_t * ui_SettingsCalibrateButtonLabel;
void ui_event_ButtonCancel(lv_event_t * e);
extern lv_obj_t * ui_ButtonCancel;
extern lv_obj_t * ui_ButtonCancelLabel;
void ui_event_ButtonOk(lv_event_t * e);
extern lv_obj_t * ui_ButtonOk;
extern lv_obj_t * ui_ButtonOkLabel;
void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Flight;
extern lv_obj_t * ui_Altitude;
extern lv_obj_t * ui_VerticalSpeed;
extern lv_obj_t * ui_GroundSpeed;
extern lv_obj_t * ui_LatLon;
extern lv_obj_t * ui_Heading;
extern lv_obj_t * ui_Registration;
extern lv_obj_t * ui_AircraftType;
extern lv_obj_t * ui_Airline;
extern lv_obj_t * ui_Origin;
extern lv_obj_t * ui_Destination;
void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Calibrate
void ui_Calibrate_screen_init(void);
extern lv_obj_t * ui_Calibrate;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_images_radar_png);    // assets\images\Radar.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
