// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Spash
void ui_Spash_screen_init(void);
void ui_event_Spash(lv_event_t * e);
extern lv_obj_t * ui_Spash;
extern lv_obj_t * ui_SplashVersion;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_TabViewSettings;
extern lv_obj_t * ui_TabPageWifi;
extern lv_obj_t * ui_SettingsWifiSsid;
extern lv_obj_t * ui_SettingsWifiSsidDropdown;
extern lv_obj_t * ui_SettingsWifiPassword;
void ui_event_SettingsWifiPasswordTextArea(lv_event_t * e);
extern lv_obj_t * ui_SettingsWifiPasswordTextArea;
extern lv_obj_t * ui_TabPageLocation;
extern lv_obj_t * ui_Label6;
void ui_event_TextAreaCitySearch(lv_event_t * e);
extern lv_obj_t * ui_TextAreaCitySearch;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_LabelCityFound;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_LabelLatLong;
extern lv_obj_t * ui_TabPageSettings;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_LabelRange;
extern lv_obj_t * ui_LabelUnits;
void ui_event_SliderRange(lv_event_t * e);
extern lv_obj_t * ui_SliderRange;
extern lv_obj_t * ui_LabelImperial;
void ui_event_SwitchImperial(lv_event_t * e);
extern lv_obj_t * ui_SwitchImperial;
void ui_event_ButtonCancel(lv_event_t * e);
extern lv_obj_t * ui_ButtonCancel;
extern lv_obj_t * ui_ButtonCancelLabel;
void ui_event_ButtonOk(lv_event_t * e);
extern lv_obj_t * ui_ButtonOk;
extern lv_obj_t * ui_ButtonOkLabel;
void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_FlightLabel;
extern lv_obj_t * ui_Flight;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_radar320x240_png);    // assets\Radar320x240.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
