// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnSplashScreenLoaded(lv_event_t * e);
void OnSettingsScreenLoaded(lv_event_t * e);
void OnCitySearchValueChanged(lv_event_t * e);
void OnSliderRangeClicked(lv_event_t * e);
void OnSwitchImperialClicked(lv_event_t * e);
void OnSettingsOkClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
