// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Calibrate_screen_init(void)
{
    ui_Calibrate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Calibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
