// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FlightLabel = lv_label_create(ui_Main);
    lv_obj_set_width(ui_FlightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FlightLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_FlightLabel, "Flight");
    lv_obj_set_style_text_color(ui_FlightLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FlightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flight = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Flight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Flight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Flight, 0);
    lv_obj_set_y(ui_Flight, 20);

    ui_Button2 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_align(ui_Button2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Settings");

    lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);

}
