// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Spash_screen_init(void)
{
    ui_Spash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Spash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Spash, &ui_img_radar320x240_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplashVersion = lv_label_create(ui_Spash);
    lv_obj_set_width(ui_SplashVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplashVersion, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_SplashVersion, "FlightRadar v1.0");
    lv_obj_set_style_bg_color(ui_SplashVersion, lv_color_hex(0x07061E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Spash);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label2, "Connecting to network");
    lv_obj_set_style_bg_color(ui_Label2, lv_color_hex(0x35457F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Spash, ui_event_Spash, LV_EVENT_ALL, NULL);

}
