// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewSettings = lv_tabview_create(ui_Settings, LV_DIR_TOP, 50);
    lv_obj_set_height(ui_TabViewSettings, 190);
    lv_obj_set_width(ui_TabViewSettings, lv_pct(100));
    lv_obj_set_align(ui_TabViewSettings, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TabViewSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_TabPageWifi = lv_tabview_add_tab(ui_TabViewSettings, "WiFi");

    ui_SettingsWifiSsid = lv_label_create(ui_TabPageWifi);
    lv_obj_set_width(ui_SettingsWifiSsid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsWifiSsid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsWifiSsid, 0);
    lv_obj_set_y(ui_SettingsWifiSsid, 10);
    lv_label_set_text(ui_SettingsWifiSsid, "SSID:");

    ui_SettingsWifiSsidDropdown = lv_dropdown_create(ui_TabPageWifi);
    lv_obj_set_width(ui_SettingsWifiSsidDropdown, 200);
    lv_obj_set_height(ui_SettingsWifiSsidDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsWifiSsidDropdown, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_SettingsWifiSsidDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_SettingsWifiPassword = lv_label_create(ui_TabPageWifi);
    lv_obj_set_width(ui_SettingsWifiPassword, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsWifiPassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsWifiPassword, 0);
    lv_obj_set_y(ui_SettingsWifiPassword, 45);
    lv_label_set_text(ui_SettingsWifiPassword, "Password:");

    ui_SettingsWifiPasswordTextArea = lv_textarea_create(ui_TabPageWifi);
    lv_obj_set_width(ui_SettingsWifiPasswordTextArea, 200);
    lv_obj_set_height(ui_SettingsWifiPasswordTextArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsWifiPasswordTextArea, 0);
    lv_obj_set_y(ui_SettingsWifiPasswordTextArea, 35);
    lv_obj_set_align(ui_SettingsWifiPasswordTextArea, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_max_length(ui_SettingsWifiPasswordTextArea, 63);
    lv_textarea_set_placeholder_text(ui_SettingsWifiPasswordTextArea, "Placeholder...");
    lv_textarea_set_password_mode(ui_SettingsWifiPasswordTextArea, true);



    ui_TabPageLocation = lv_tabview_add_tab(ui_TabViewSettings, "Location");

    ui_Label6 = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 10);
    lv_label_set_text(ui_Label6, "Search:");

    ui_TextAreaCitySearch = lv_textarea_create(ui_TabPageLocation);
    lv_obj_set_width(ui_TextAreaCitySearch, 220);
    lv_obj_set_height(ui_TextAreaCitySearch, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_TextAreaCitySearch, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_placeholder_text(ui_TextAreaCitySearch, "Placeholder...");



    ui_Label5 = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 45);
    lv_label_set_text(ui_Label5, "Found:");

    ui_LabelCityFound = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LabelCityFound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCityFound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCityFound, 80);
    lv_obj_set_y(ui_LabelCityFound, 45);
    lv_label_set_text(ui_LabelCityFound, "-");

    ui_Label3 = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 80);
    lv_label_set_text(ui_Label3, "Lat/Long:");

    ui_LabelLatLong = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LabelLatLong, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLatLong, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLatLong, 80);
    lv_obj_set_y(ui_LabelLatLong, 80);
    lv_label_set_text(ui_LabelLatLong, "-");

    ui_TabPageSettings = lv_tabview_add_tab(ui_TabViewSettings, "Settings");

    ui_Label21 = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, 10);
    lv_label_set_text(ui_Label21, "Range:");

    ui_LabelRange = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_LabelRange, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRange, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRange, 60);
    lv_obj_set_y(ui_LabelRange, 10);
    lv_label_set_text(ui_LabelRange, "-");

    ui_LabelUnits = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_LabelUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnits, 100);
    lv_obj_set_y(ui_LabelUnits, 10);
    lv_label_set_text(ui_LabelUnits, "-");

    ui_SliderRange = lv_slider_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SliderRange, 150);
    lv_obj_set_height(ui_SliderRange, 10);
    lv_obj_set_y(ui_SliderRange, 10);
    lv_obj_set_x(ui_SliderRange, lv_pct(0));
    lv_obj_set_align(ui_SliderRange, LV_ALIGN_TOP_RIGHT);


    ui_LabelImperial = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_LabelImperial, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelImperial, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelImperial, 0);
    lv_obj_set_y(ui_LabelImperial, 45);
    lv_label_set_text(ui_LabelImperial, "Imperial units:");

    ui_SwitchImperial = lv_switch_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SwitchImperial, 50);
    lv_obj_set_height(ui_SwitchImperial, 25);
    lv_obj_set_x(ui_SwitchImperial, 0);
    lv_obj_set_y(ui_SwitchImperial, 40);
    lv_obj_set_align(ui_SwitchImperial, LV_ALIGN_TOP_RIGHT);


    ui_ButtonCancel = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_ButtonCancel, 100);
    lv_obj_set_height(ui_ButtonCancel, 40);
    lv_obj_set_align(ui_ButtonCancel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonCancelLabel = lv_label_create(ui_ButtonCancel);
    lv_obj_set_width(ui_ButtonCancelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonCancelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonCancelLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonCancelLabel, "Cancel");

    ui_ButtonOk = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_ButtonOk, 100);
    lv_obj_set_height(ui_ButtonOk, 40);
    lv_obj_set_align(ui_ButtonOk, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ButtonOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonOkLabel = lv_label_create(ui_ButtonOk);
    lv_obj_set_width(ui_ButtonOkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonOkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonOkLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonOkLabel, "OK");

    ui_Keyboard2 = lv_keyboard_create(ui_Settings);
    lv_obj_set_height(ui_Keyboard2, 100);
    lv_obj_set_width(ui_Keyboard2, lv_pct(100));
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_SettingsWifiPasswordTextArea, ui_event_SettingsWifiPasswordTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaCitySearch, ui_event_TextAreaCitySearch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderRange, ui_event_SliderRange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchImperial, ui_event_SwitchImperial, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCancel, ui_event_ButtonCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOk, ui_event_ButtonOk, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
