// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewSettings = lv_tabview_create(ui_Settings, LV_DIR_TOP, 50);
    lv_obj_set_height(ui_TabViewSettings, 190);
    lv_obj_set_width(ui_TabViewSettings, lv_pct(100));
    lv_obj_set_align(ui_TabViewSettings, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TabViewSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_TabPageWifi = lv_tabview_add_tab(ui_TabViewSettings, "WiFi");

    ui_WifiSsidLabel = lv_label_create(ui_TabPageWifi);
    lv_obj_set_width(ui_WifiSsidLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSsidLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiSsidLabel, 0);
    lv_obj_set_y(ui_WifiSsidLabel, 10);
    lv_label_set_text(ui_WifiSsidLabel, "SSID:");

    ui_WifiSsidDropdown = lv_dropdown_create(ui_TabPageWifi);
    lv_dropdown_set_options(ui_WifiSsidDropdown, "Searching...");
    lv_obj_set_width(ui_WifiSsidDropdown, 200);
    lv_obj_set_height(ui_WifiSsidDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSsidDropdown, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_WifiSsidDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_WifiPasswordLabel = lv_label_create(ui_TabPageWifi);
    lv_obj_set_width(ui_WifiPasswordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiPasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiPasswordLabel, 0);
    lv_obj_set_y(ui_WifiPasswordLabel, 45);
    lv_label_set_text(ui_WifiPasswordLabel, "Password:");

    ui_WifiPasswordTextArea = lv_textarea_create(ui_TabPageWifi);
    lv_obj_set_width(ui_WifiPasswordTextArea, 200);
    lv_obj_set_height(ui_WifiPasswordTextArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiPasswordTextArea, 0);
    lv_obj_set_y(ui_WifiPasswordTextArea, 35);
    lv_obj_set_align(ui_WifiPasswordTextArea, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_max_length(ui_WifiPasswordTextArea, 63);
    lv_textarea_set_placeholder_text(ui_WifiPasswordTextArea, "Enter password");
    lv_textarea_set_one_line(ui_WifiPasswordTextArea, true);
    lv_textarea_set_password_mode(ui_WifiPasswordTextArea, true);



    ui_TabPageLocation = lv_tabview_add_tab(ui_TabViewSettings, "Location");

    ui_LocationSearchLabel = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LocationSearchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LocationSearchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LocationSearchLabel, 0);
    lv_obj_set_y(ui_LocationSearchLabel, 10);
    lv_label_set_text(ui_LocationSearchLabel, "Search:");

    ui_LocationSearchTextArea = lv_textarea_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LocationSearchTextArea, 220);
    lv_obj_set_height(ui_LocationSearchTextArea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_LocationSearchTextArea, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_placeholder_text(ui_LocationSearchTextArea, "Type location to start search");



    ui_LocationFoundLabel = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LocationFoundLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LocationFoundLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LocationFoundLabel, 0);
    lv_obj_set_y(ui_LocationFoundLabel, 45);
    lv_label_set_text(ui_LocationFoundLabel, "Found:");

    ui_LocationFoundValueLabel = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LocationFoundValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LocationFoundValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LocationFoundValueLabel, 80);
    lv_obj_set_y(ui_LocationFoundValueLabel, 45);
    lv_label_set_text(ui_LocationFoundValueLabel, "-");

    ui_LocationLatLonLabel = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LocationLatLonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LocationLatLonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LocationLatLonLabel, 0);
    lv_obj_set_y(ui_LocationLatLonLabel, 80);
    lv_label_set_text(ui_LocationLatLonLabel, "Lat/Long:");

    ui_LabelLatLong = lv_label_create(ui_TabPageLocation);
    lv_obj_set_width(ui_LabelLatLong, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLatLong, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLatLong, 80);
    lv_obj_set_y(ui_LabelLatLong, 80);
    lv_label_set_text(ui_LabelLatLong, "-");

    ui_TabPageSettings = lv_tabview_add_tab(ui_TabViewSettings, "Settings");

    ui_SettingsRangeLabel = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SettingsRangeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsRangeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsRangeLabel, 0);
    lv_obj_set_y(ui_SettingsRangeLabel, 10);
    lv_label_set_text(ui_SettingsRangeLabel, "Range:");

    ui_SettingsRange = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SettingsRange, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsRange, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsRange, 60);
    lv_obj_set_y(ui_SettingsRange, 10);
    lv_label_set_text(ui_SettingsRange, "-");

    ui_SettingsUnitsLabel = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SettingsUnitsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsUnitsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsUnitsLabel, 100);
    lv_obj_set_y(ui_SettingsUnitsLabel, 10);
    lv_label_set_text(ui_SettingsUnitsLabel, "-");

    ui_SettingsRangeSlider = lv_slider_create(ui_TabPageSettings);
    lv_slider_set_range(ui_SettingsRangeSlider, 5, 50);
    lv_obj_set_width(ui_SettingsRangeSlider, 150);
    lv_obj_set_height(ui_SettingsRangeSlider, 10);
    lv_obj_set_y(ui_SettingsRangeSlider, 10);
    lv_obj_set_x(ui_SettingsRangeSlider, lv_pct(0));
    lv_obj_set_align(ui_SettingsRangeSlider, LV_ALIGN_TOP_RIGHT);


    ui_SettingsImperialLabel = lv_label_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SettingsImperialLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImperialLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsImperialLabel, 0);
    lv_obj_set_y(ui_SettingsImperialLabel, 45);
    lv_label_set_text(ui_SettingsImperialLabel, "Imperial units:");

    ui_SettingsImperialSwitch = lv_switch_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SettingsImperialSwitch, 50);
    lv_obj_set_height(ui_SettingsImperialSwitch, 25);
    lv_obj_set_x(ui_SettingsImperialSwitch, 0);
    lv_obj_set_y(ui_SettingsImperialSwitch, 40);
    lv_obj_set_align(ui_SettingsImperialSwitch, LV_ALIGN_TOP_RIGHT);


    ui_SettingsCalibrateButton = lv_btn_create(ui_TabPageSettings);
    lv_obj_set_width(ui_SettingsCalibrateButton, 100);
    lv_obj_set_height(ui_SettingsCalibrateButton, 50);
    lv_obj_set_x(ui_SettingsCalibrateButton, 0);
    lv_obj_set_y(ui_SettingsCalibrateButton, 70);
    lv_obj_set_align(ui_SettingsCalibrateButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SettingsCalibrateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsCalibrateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsCalibrateButtonLabel = lv_label_create(ui_SettingsCalibrateButton);
    lv_obj_set_width(ui_SettingsCalibrateButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsCalibrateButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsCalibrateButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsCalibrateButtonLabel, "Calibrate");

    ui_ButtonCancel = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_ButtonCancel, 100);
    lv_obj_set_height(ui_ButtonCancel, 40);
    lv_obj_set_align(ui_ButtonCancel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonCancelLabel = lv_label_create(ui_ButtonCancel);
    lv_obj_set_width(ui_ButtonCancelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonCancelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonCancelLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonCancelLabel, "Cancel");

    ui_ButtonOk = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_ButtonOk, 100);
    lv_obj_set_height(ui_ButtonOk, 40);
    lv_obj_set_align(ui_ButtonOk, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ButtonOk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonOkLabel = lv_label_create(ui_ButtonOk);
    lv_obj_set_width(ui_ButtonOkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonOkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonOkLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonOkLabel, "OK");

    ui_Keyboard2 = lv_keyboard_create(ui_Settings);
    lv_obj_set_height(ui_Keyboard2, 100);
    lv_obj_set_width(ui_Keyboard2, lv_pct(100));
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_WifiPasswordTextArea, ui_event_WifiPasswordTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LocationSearchTextArea, ui_event_LocationSearchTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsRangeSlider, ui_event_SettingsRangeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsImperialSwitch, ui_event_SettingsImperialSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsCalibrateButton, ui_event_SettingsCalibrateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCancel, ui_event_ButtonCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOk, ui_event_ButtonOk, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
